<p><img src="https://www.paymee.com.br/wp-content/uploads/2019/07/PayMee_New.png" width="120" height="30"/></p>
<p><?php echo $this->escapeHtml($this->__($this->getMethod()->getTitle())) ?></p>
<?php
$orderId    = $this->getInfo()->getParentId();
$order      = Mage::getModel('sales/order')->load($orderId);

?>

<?php
if ($this->getMethod()->getCode() == 'juniormaia_paymee_pix') {

    Mage::log($this->getInfo()->getAdditionalInformation());

    if ($this->getInfo()->getAdditionalInformation('paymee_pix_qrcode')) {
        $qrcode = $this->getInfo()->getAdditionalInformation('paymee_pix_qrcode');
        echo "<img id='barcode' src='".$qrcode."' title='PayMee' width='200' height='200' />";
    }
    if ($this->getInfo()->getAdditionalInformation('paymee_pix_plain')) {
        echo "<p>".$this->__('Copia e Cola: <strong>%s</strong>', $this->getInfo()->getAdditionalInformation('paymee_pix_plain'))."</p>";
    }
}
?>

<?php

if ($this->getMethod()->getCode() == 'juniormaia_paymee_transfer') {
    if ($this->getInfo()->getAdditionalInformation('paymee_cpf')) {
        echo "<p>".$this->__('CPF: <strong>%s</strong>', $this->getInfo()->getAdditionalInformation('paymee_cpf'))."</p>";
    }

    if ($this->getInfo()->getAdditionalInformation('paymee_branch')) {
        echo "<p>".$this->__('Minha Agência: <strong>%s</strong>', $this->getInfo()->getAdditionalInformation('paymee_branch'))."</p>";
    }

    if ($this->getInfo()->getAdditionalInformation('paymee_account')) {
        echo "<p>".$this->__('Minha Conta: <strong>%s</strong>', $this->getInfo()->getAdditionalInformation('paymee_account'))."</p>";
    }

    if ($this->getInfo()->getAdditionalInformation('paymee_response')) {
        $response_payload   = $this->getInfo()->getAdditionalInformation('paymee_response');
        $response           = json_decode($response_payload, true);
        $instructions       = $response['response']['instructions'];
        $uuid               = $response['response']['uuid'];

        echo "<p><b>Tranferir para:</b></p>";
        echo "<p>".$this->__('Banco: <strong>%s</strong>', $instructions['name'])."</p>";
        echo "<p>".$this->__('Beneficiário: <strong>%s</strong>', $instructions['beneficiary_name'])."</p>";
        echo "<p>".$this->__('Agência: <strong>%s</strong>', $instructions['beneficiary_branch'])."</p>";
        echo "<p>".$this->__('Conta: <strong>%s</strong>', $instructions['beneficiary_account'])."</p>";
        echo "<p>".$this->__('CNPJ: <strong>%s</strong>', $instructions['beneficiary_document'])."</p>";
        echo "<a href='https://checkout.paymee.com.br/".$uuid."' target='_blank'>Clique aqui para transferir</a>";
    }
}
?>